### PR TITLE
implement mixed sdist/wheel packages & test case

### PR DESCRIPTION
**Pull request by TyberiusPrime**
By reading [tool.uv] no-binary-packages / no-build-packages.

### CODE REVIEW

**Comment by adisbladis** [comment]
I moved the tests from integration tests to unit tests instead, fixed some structure for a little bit better performance (putting the list computation higher up in scope), and also taking root-level virtual workspace config into account.

What I'd still like to see is:

- Docs
  This is a great feature, but it's not super discoverable without documentation.

- Support for `no-binary` & `no-build`'s non-package equivalents
  https://docs.astral.sh/uv/reference/settings/#no-binary
  https://docs.astral.sh/uv/reference/settings/#no-build

**Comment by TyberiusPrime** [comment]
Thank you. Especially for polishing this nugget of an implementation.
The test is much better as a unit test.

I should be able to stick to the pattern for the top-level options. Going to be interesting when workplaces mix them.

Question: do you want to keep sourcePref as an option, or rely only on non-binary/no-build?

**Comment by adisbladis** [comment]
> Going to be interesting when workplaces mix them.

I'm thinking that the way to do that is to fold over workspaces returning a nullable bool, then we could throw on a mismatch.

> Question: do you want to keep sourcePref as an option, or rely only on non-binary/no-build?

Neither option defines what you'd want to do as a default.
Python package managers default to using prebuilt wheels, but in Nix people tend to want source based builds.
I think it's important that users understand that distinction up-front, because it shapes how much overriding they'll have to do.

**Comment by adisbladis** [comment]
no-build & no-binary was added in 859476c2b78a43792bded8ef381fd9b4d1a8a3ef

**Comment by TyberiusPrime** [comment]
Ok, so I understand it when drafting docs:

 1. uv no-build/no-binary are prescriptive. We fail if we can't fulfill the request.
 1. sourcePreference is a 'soft' in the sense that uv2nix is free to fall back to the other one if there is no matching wheel(/source) available.
 1. in uv, there is no overwriting no-build with individual no-binary-packages ('building source distribution is disabled') And uv2nix does the same, message: `Package source for 'anndata' was derived as wheel, but was present in tool.uv.no-binary-package`)
 1. but in uv, apparently you can overwrite no-binary with no-build-package, but uv2nix does reject this. (`Package source for 'numpy' was derived as sdist, but was present in tool.uv.no-build-package`)

to show  3:
```
no-binary-package = ['test-wheel-wheel-test']
no-build=true
```
fails. (also fails without no-build true because... idk, but with different error message?
Seems uv does not fall back to the sdist in this case?).

to show 4: 
```
no-build-package=['test-wheel-wheel-test']
no-binary=true
```

And then there's only ['only-binary'](https://docs.astral.sh/uv/reference/settings/#pip_only-binary), which apparently is so brand new the 0.4.4 in nixpkgs master doesn't know about it yet.

These options seem to be evolving in uv at the moment as well.

**Comment by adisbladis** [comment]
> but in uv, apparently you can overwrite no-binary with no-build-package, but uv2nix does reject this. (Package source for 'numpy' was derived as sdist, but was present in tool.uv.no-build-package)

How is this supposed to work?
You say no-binary, but also not to build those packages? Are you perhaps using locally cached wheels in uv?

> And then there's only ['only-binary'](https://docs.astral.sh/uv/reference/settings/#pip_only-binary), which apparently is so brand new the 0.4.4 in nixpkgs master doesn't know about it yet.

That's in the section specific to `uv pip`, and not relevant to us.

**Comment by TyberiusPrime** [comment]
> You say no-binary, but also not to build those packages? Are you perhaps using locally cached wheels in uv?

I just pulled up an fresh container to test. Empty /home.
Now I'm three quarters convinced this stuff is just broken in 0.4.4.

Saying 'no-binary=true' leads to 
"Using pre-built wheels is disabled, but attempted to use `test-wheel-wheel-test`".
(this package does have a sourced dist...)

But saying no-binary=true and no-build-package=["test-wheel-wheel-test"] will install the wheel.


Let's keep the current uv2nix behavior, 
and revisit this some uv releases later.

**Comment by adisbladis** [comment]
I've moved the config loading over to `workspace` in 5b36429530387ce85cc586788eca54693602dea7 and made auto-loaded config user overridable.

**Pull request merged**
